const express = require('express')
const CustomerRouter = express.Router()
const {register,login,logout} = require('../authentication/loginsignup.authentication')
const {auth,isOwner}= require("../middleware/auth.middleware")
const {additems,updateitems,deleteItems}= require("../controller/Owner/CrudItems")
const {addToCart,viewTocart}= require("../controller/Customer/Order")
const DashBoard= require("../controller/Customer/dashboard.customer")
// user
CustomerRouter.post('/user/register', register)
CustomerRouter.post('/user/login', login)
CustomerRouter.post('/user/logout', logout)
CustomerRouter.post('/user/logout', logout)
CustomerRouter.post('/task/addtocart',auth, addToCart)
CustomerRouter.get('/task/dashboard',auth, DashBoard)
CustomerRouter.get('/task/viewowncart',auth, viewTocart)
module.exports = CustomerRouter